services:
  zookeeper:
    image: zookeeper
    container_name: my_zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - networkName

  kafka:
    image: apache/kafka
    container_name: my_kafkaserver
    depends_on:
      - zookeeper
    restart: always
    ports:
      - "9092:9092"
    networks:
      - networkName

  postgres:
    image: postgres
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  networkName: